spring.application.name=activityservice
server.port = 8080
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

springdoc.swagger-ui.path=/swagger.html
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/soa
spring.datasource.username=steve
spring.datasource.password=steve123
spring.jpa.show-sql: true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always